config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "subscribers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, format: /\+\d+ \d+ \d{6,}/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: %i[ show edit update destroy ]

  # GET /subscribers or /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1 or /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers or /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to subscriber_url(@subscriber), notice: "Subscriber was successfully created." }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1 or /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to subscriber_url(@subscriber), notice: "Subscriber was successfully updated." }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1 or /subscribers/1.json
  def destroy
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: "Subscriber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscriber_params
      params.require(:subscriber).permit(:first_name, :last_name, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subscribers/_form.html.erb
<%= form_with(model: subscriber) do |form| %>
  <% if subscriber.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
        <% subscriber.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribers/_subscriber.html.erb
<div id="<%= dom_id subscriber %>">
  <p>
    <strong>First name:</strong>
    <%= subscriber.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= subscriber.last_name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= subscriber.phone_number %>
  </p>

</div>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render "form", subscriber: @subscriber %>

<br>

<div>
  <%= link_to "Show this subscriber", @subscriber %> |
  <%= link_to "Back to subscribers", subscribers_path %>
</div>

app/views/subscribers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscribers</h1>

<div id="subscribers">
  <% @subscribers.each do |subscriber| %>
    <%= render subscriber %>
    <p>
      <%= link_to "Show this subscriber", subscriber %>
    </p>
  <% end %>
</div>

<%= link_to "New subscriber", new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render "form", subscriber: @subscriber %>

<br>

<div>
  <%= link_to "Back to subscribers", subscribers_path %>
</div>

app/views/subscribers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscriber %>

<div>
  <%= link_to "Edit this subscriber", edit_subscriber_path(@subscriber) %> |
  <%= link_to "Back to subscribers", subscribers_path %>

  <%= button_to "Destroy this subscriber", @subscriber, method: :delete %>
</div>